#cgates/jebene: 7/9/2014

language: python
python:
    - "2.7"

#virtualenv:
#   system_site_packages: true

install: "pip install -r requirements.txt"
 
script: nosetests

notifications:
    email:
        - cgates@umich.edu
        - jebene@umich.edu
